# Generated by Django 3.2.3 on 2021-06-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('tell', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default='2021-06-09', null=True)),
                ('Total', models.PositiveIntegerField(default=0)),
                ('statusOrder', models.BooleanField()),
                ('mem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.member')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=5)),
                ('image_file', models.ImageField(upload_to='Payment/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=5)),
                ('image_file', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sizes_id', models.AutoField(primary_key=True, serialize=False)),
                ('sizes_pro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('cate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.category')),
                ('sizes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.size')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateTimeField(default='2021-06-09', null=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_de_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('Totals', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.order')),
                ('pro_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Total', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.member')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('Totals', models.IntegerField(default=0)),
                ('cart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.carts')),
                ('pro_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product')),
            ],
        ),
    ]
