# Generated by Django 3.2.3 on 2021-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210617_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='Total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
