# Generated by Django 3.2.3 on 2021-06-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210619_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.carts'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.member'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.member'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mem_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.member'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='pro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.size'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.member'),
        ),
    ]
