# Generated by Django 3.2.4 on 2021-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20210621_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default='2021-07-02', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateTimeField(default='2021-07-02', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
